import { LectureContentType } from "@/enum";

export const sampleModules = [
  {
    id: "mod-1",
    title: "Introduction to Web Development",
    courseId: "course-1",
    moduleNumber: 1,
    isFree: true,
    lectures: [
      {
        id: "lec-1-1",
        title: "What is Web Development?",
        moduleId: "mod-1",
        content: "An overview of web development basics.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-1-2",
        title: "Frontend vs Backend",
        moduleId: "mod-1",
        content: "Understanding the difference between frontend and backend.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-1-3",
        title: "Setting Up Your Environment",
        moduleId: "mod-1",
        content: "Installing Node.js, VSCode, and Git.",
        contentType: LectureContentType.Text,
      },
      {
        id: "lec-1-4",
        title: "Hello World in HTML",
        moduleId: "mod-1",
        content: "Your first HTML page.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-1-5",
        title: "Course Overview",
        moduleId: "mod-1",
        content: "What you'll learn in this course.",
        contentType: LectureContentType.Text,
      },
    ],
  },
  {
    id: "mod-2",
    title: "HTML Basics",
    courseId: "course-1",
    moduleNumber: 2,
    isFree: false,
    lectures: [
      {
        id: "lec-2-1",
        title: "HTML Tags & Structure",
        moduleId: "mod-2",
        content: "Basic tags and document structure.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-2-2",
        title: "Headings, Paragraphs & Lists",
        moduleId: "mod-2",
        content: "Organizing content with headings and lists.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-2-3",
        title: "Links & Images",
        moduleId: "mod-2",
        content: "Adding links and images in HTML.",
        contentType: LectureContentType.Text,
      },
      {
        id: "lec-2-4",
        title: "Tables & Forms",
        moduleId: "mod-2",
        content: "Creating tables and forms.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-2-5",
        title: "Semantic HTML",
        moduleId: "mod-2",
        content: "Using semantic tags for better accessibility.",
        contentType: LectureContentType.Text,
      },
    ],
  },
  {
    id: "mod-3",
    title: "CSS Fundamentals",
    courseId: "course-1",
    moduleNumber: 3,
    isFree: false,
    lectures: [
      {
        id: "lec-3-1",
        title: "What is CSS?",
        moduleId: "mod-3",
        content: "Introduction to styling with CSS.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-3-2",
        title: "Selectors & Properties",
        moduleId: "mod-3",
        content: "Using selectors and properties in CSS.",
        contentType: LectureContentType.Text,
      },
      {
        id: "lec-3-3",
        title: "Colors & Typography",
        moduleId: "mod-3",
        content: "Working with colors and fonts.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-3-4",
        title: "Box Model & Spacing",
        moduleId: "mod-3",
        content: "Margins, padding, and borders explained.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-3-5",
        title: "CSS Positioning",
        moduleId: "mod-3",
        content: "Positioning elements on a page.",
        contentType: LectureContentType.Text,
      },
    ],
  },
  {
    id: "mod-4",
    title: "JavaScript Basics",
    courseId: "course-1",
    moduleNumber: 4,
    isFree: false,
    lectures: [
      {
        id: "lec-4-1",
        title: "Intro to JavaScript",
        moduleId: "mod-4",
        content: "JavaScript basics and syntax.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-4-2",
        title: "Variables & Data Types",
        moduleId: "mod-4",
        content: "Different data types in JS.",
        contentType: LectureContentType.Text,
      },
      {
        id: "lec-4-3",
        title: "Functions & Scope",
        moduleId: "mod-4",
        content: "How to write and use functions.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-4-4",
        title: "DOM Manipulation",
        moduleId: "mod-4",
        content: "How JavaScript interacts with HTML.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-4-5",
        title: "Events & Listeners",
        moduleId: "mod-4",
        content: "Handling user interactions.",
        contentType: LectureContentType.Text,
      },
    ],
  },
  {
    id: "mod-5",
    title: "Final Project",
    courseId: "course-1",
    moduleNumber: 5,
    isFree: false,
    lectures: [
      {
        id: "lec-5-1",
        title: "Project Setup",
        moduleId: "mod-5",
        content: "Setting up your final project.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-5-2",
        title: "Building the Layout",
        moduleId: "mod-5",
        content: "Creating structure with HTML and CSS.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-5-3",
        title: "Adding Interactivity",
        moduleId: "mod-5",
        content: "Using JavaScript to add features.",
        contentType: LectureContentType.Video,
      },
      {
        id: "lec-5-4",
        title: "Debugging & Testing",
        moduleId: "mod-5",
        content: "How to test and debug your project.",
        contentType: LectureContentType.Text,
      },
      {
        id: "lec-5-5",
        title: "Project Submission",
        moduleId: "mod-5",
        content: "Submitting and showcasing your work.",
        contentType: LectureContentType.Text,
      },
    ],
  },
];
